### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by Killermops12** [CaffeinatedDave/lifx-server#2]
There seems to be an issue between the LIFX server an my bulbs as they are connected to my wifi but can not be deleted or controled...

**Comment by CaffeinatedDave** [comment]
Hi Killermops12 - I'm afraid you've found an old repo that hasn't been maintained since LIFX launched a mobile app that did everything I wanted this to do...

Can I ask how you have this application set up/running so far - I can see if I can get it to connect for you.

**Comment by CaffeinatedDave** [comment]
No follow up - closing this as unreproducable
